### PR TITLE
Prepare for icon removal from core

### PR DESCRIPTION
**Pull request by NotMyFault**
@olivergondza Preparation for https://github.com/jenkinsci/jenkins/pull/5778

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did

### CODE REVIEW

**Comment by NotMyFault** [comment]
@olivergondza Any chance to get this merged and released soon?

**Comment by NotMyFault** [comment]
@olivergondza Any chance to get this merged and released soon?

**Review by MarkEWaite — APPROVED** [review]
Technique is working in other plugins.

**Comment by MarkEWaite** [comment]
@olivergondza I did an octopus merge of this pull request, #10, and #11 and am using it in my Jenkins installation.  Would love to have those three merged so that they could be referenced as an incremental build in [my plugins.txt file](https://github.com/MarkEWaite/docker-lfs/blob/87fd69764896b6b9ade833f8b40d68e506724d83/plugins.txt#L89).

Would also be most grateful if you were able to release a version from the master branch after merging those three pull requests.

**Comment by NotMyFault** [comment]
The next LTS baseline selection is coming up very soon, which includes the icon removal from core. Could you please take care of this PR and trigger a release of afterwards, to prepare it for the removal? @olivergondza

**Comment by MarkEWaite** [comment]
@olivergondza if you are willing, I would be happy to be granted permission to help with maintaining this plugin.  I use it very much and appreciate how it helps me.

**Comment by NotMyFault** [comment]
Thanks for stepping up, Mark. Finally I can move this PR onto my next spreadsheet 👏🏻

**Pull request merged**
